FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir poetry==2.4.1

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false && \
    poetry install --only main --no-root --no-interaction --no-ansi

COPY create_file_txt.py .
COPY transform_txt_in_csv.py .
COPY main.py .

RUN mkdir -p /app/entrada /app/saida

CMD ["python", "main.py"]